- name: Configure licensing
  hosts: all
  gather_facts: no
  connection: network_cli
  become: yes
  become_method: enable
  tags:
    - register
  vars:
    smart_licensing:
      idtoken: MzY3NDdmYWUtMjFmYy00ZDM3LTk0MGEtMzRjYWRjMDdjYmZlLTE2MTI5NzY0%0AODgyOTZ8WkJpVVgrZ2NLdlNSaGFIS1BhejJQQ3lZRzIyalNab0RMZmdRSnZO%0AR3pSWT0%3D%0A
    satellite_ip: 10.81.106.236
    satellite_user: admin
    satellite_password: #satellite_pw
  tasks:
    - name: disable default callhome URL
      ios_config:
        lines:
          - "license smart enable"
          - "call-home"
          - "profile CiscoTAC-1"
          - "destination address http http://{{ satellite_ip }}/Transportgateway/services/DeviceRequestHandler"
          - "no destination address http https://tools.cisco.com/its/service/oddce/services/DDCEService"
        save_when: modified

    - name: Register with idtoken
      ios_command:
        commands:
          - command: license smart register idtoken {{ smart_licensing.idtoken }}

    - name: enable service internal
      ios_config:
        lines:
          - "service internal"
        save_when: modified

    - name: start conversion
      ios_command:
        commands:
          - command: test license smart conversion enable
          - command: license smart conversion start

    - name: Reloading the Switch
      ios_command:
        commands:
          - command: reload
            prompt: [confirm]
            answer: "\r"

    - name: Reset the persitent SSH connection
      meta: reset_connection

    - name: Wait for device to come back up
      wait_for:
        port: 22
        timeout: 1800
        host: "{{ ansible_host }}"
        delay: 300
      delegate_to: localhost

    - name: Waiting for successful registration
      ios_command:
        commands:
          - show license status
      register: license_status
      until: "'AUTHORIZED' in license_status.stdout[0]"
      retries: 60
      delay: 10

    - name: Force full sync on OnPrem
      uri:
        url: 'https://{{ satellite_ip }}:8443/backend/sync/upstream_satellites/sync.json?satellite_id=1&sync_type=full'
        method: PUT
        body: '{"sync_account_id":1,"exclude_hostname":false,"exclude_ipaddress":false,"exclude_macaddress":false}'
        body_format: json
        headers:
            Content-Type: 'text/plain'
        url_username: '{{ satellite_user }}'
        url_password: '{{ satellite_password }}'
        validate_certs: no
      register: result
    
    - name: Wait for full sync to complete
      pause:
        minutes: 7

    - name: Force full sync on OnPrem
      uri:
        url: 'https://{{ satellite_ip }}:8443/backend/sync/upstream_satellites/sync.json?satellite_id=1&sync_type=full'
        method: PUT
        body: '{"sync_account_id":1,"exclude_hostname":false,"exclude_ipaddress":false,"exclude_macaddress":false}'
        body_format: json
        headers:
            Content-Type: 'text/plain'
        url_username: '{{ satellite_user }}'
        url_password: '{{ satellite_password }}'
        validate_certs: no
      register: result

    - name: Wait for full sync to complete
      pause:
        minutes: 2

    - name: License renew auth
      ios_command:
        commands:
          - command: license smart renew auth